-- MySQL Script generated by MySQL Workbench
-- Sat Oct 12 17:00:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smartmsph
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartmsph` ;

-- -----------------------------------------------------
-- Schema smartmsph
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartmsph` DEFAULT CHARACTER SET utf8 ;
USE `smartmsph` ;

-- -----------------------------------------------------
-- Table `smartmsph`.`administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartmsph`.`administrator` ;

CREATE TABLE IF NOT EXISTS `smartmsph`.`administrator` (
  `id` INT(11) NOT NULL,
  `administratorname` VARCHAR(45) NOT NULL,
  `surname1` VARCHAR(45) NOT NULL,
  `surname2` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `department_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_administrator_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `smartmsph`.`department` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_UNIQUE` ON `smartmsph`.`administrator` (`id` ASC) VISIBLE;

CREATE INDEX `fk_administrator_department1_idx` ON `smartmsph`.`administrator` (`department_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartmsph`.`citizen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartmsph`.`citizen` ;

CREATE TABLE IF NOT EXISTS `smartmsph`.`citizen` (
  `id` INT(11) NOT NULL,
  `citizenname` VARCHAR(45) NOT NULL,
  `surname1` VARCHAR(45) NOT NULL,
  `surname2` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_UNIQUE` ON `smartmsph`.`citizen` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartmsph`.`citizen_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartmsph`.`citizen_user` ;

CREATE TABLE IF NOT EXISTS `smartmsph`.`citizen_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `citizen_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_citizen_user_citizen1`
    FOREIGN KEY (`citizen_id`)
    REFERENCES `smartmsph`.`citizen` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_UNIQUE` ON `smartmsph`.`citizen_user` (`id` ASC) VISIBLE;

CREATE INDEX `fk_citizen_user_citizen1_idx` ON `smartmsph`.`citizen_user` (`citizen_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartmsph`.`complain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartmsph`.`complain` ;

CREATE TABLE IF NOT EXISTS `smartmsph`.`complain` (
  `id` INT(11) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `ticket_id` INT(11) NOT NULL,
  `citizen_id` INT(11) NOT NULL,
  `photo` LONGBLOB NULL,
  PRIMARY KEY (`id`, `ticket_id`),
  CONSTRAINT `fk_complain_citizen1`
    FOREIGN KEY (`citizen_id`)
    REFERENCES `smartmsph`.`citizen` (`id`),
  CONSTRAINT `fk_complain_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `smartmsph`.`ticket` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_complain_ticket1_idx` ON `smartmsph`.`complain` (`ticket_id` ASC) VISIBLE;

CREATE INDEX `fk_complain_citizen1_idx` ON `smartmsph`.`complain` (`citizen_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartmsph`.`denounces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartmsph`.`denounces` ;

CREATE TABLE IF NOT EXISTS `smartmsph`.`denounces` (
  `id` INT(11) NOT NULL,
  `description` VARCHAR(3999) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `ticket_id` INT(11) NOT NULL,
  `citizen_id` INT(11) NOT NULL,
  `photo` LONGBLOB NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `ticket_id`),
  CONSTRAINT `fk_denounces_citizen1`
    FOREIGN KEY (`citizen_id`)
    REFERENCES `smartmsph`.`citizen` (`id`),
  CONSTRAINT `fk_denounces_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `smartmsph`.`ticket` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_denounces_ticket1_idx` ON `smartmsph`.`denounces` (`ticket_id` ASC) VISIBLE;

CREATE INDEX `fk_denounces_citizen1_idx` ON `smartmsph`.`denounces` (`citizen_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartmsph`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartmsph`.`department` ;

CREATE TABLE IF NOT EXISTS `smartmsph`.`department` (
  `id` INT(11) NOT NULL,
  `departmentname` VARCHAR(45) NULL DEFAULT NULL,
  `administrator_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_department_administrator1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `smartmsph`.`administrator` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_UNIQUE` ON `smartmsph`.`department` (`id` ASC) VISIBLE;

CREATE INDEX `fk_department_administrator1_idx` ON `smartmsph`.`department` (`administrator_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartmsph`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartmsph`.`news` ;

CREATE TABLE IF NOT EXISTS `smartmsph`.`news` (
  `id` INT(11) NOT NULL,
  `decription` VARCHAR(45) NULL DEFAULT NULL,
  `department_id` INT(11) NOT NULL,
  `photo1` LONGBLOB NULL,
  `photo2` LONGBLOB NULL,
  `photo3` LONGBLOB NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_news_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `smartmsph`.`department` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_news_department1_idx` ON `smartmsph`.`news` (`department_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartmsph`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartmsph`.`ticket` ;

CREATE TABLE IF NOT EXISTS `smartmsph`.`ticket` (
  `id` INT(11) NOT NULL,
  `department_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ticket_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `smartmsph`.`department` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_ticket_department1_idx` ON `smartmsph`.`ticket` (`department_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartmsph`.`user_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartmsph`.`user_admin` ;

CREATE TABLE IF NOT EXISTS `smartmsph`.`user_admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `administrator_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_admin_administrator1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `smartmsph`.`administrator` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_UNIQUE` ON `smartmsph`.`user_admin` (`id` ASC) VISIBLE;

CREATE INDEX `fk_user_admin_administrator1_idx` ON `smartmsph`.`user_admin` (`administrator_id` ASC) VISIBLE;

USE `smartmsph` ;

-- -----------------------------------------------------
-- Placeholder table for view `smartmsph`.`rep_citizen_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartmsph`.`rep_citizen_user` (`idcitizen` INT, `citizenname` INT, `surname1` INT, `surname2` INT, `mail` INT, `phoneNumber` INT, `iduser` INT, `username` INT, `password` INT, `role` INT, `citizen_id` INT);

-- -----------------------------------------------------
-- View `smartmsph`.`rep_citizen_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartmsph`.`rep_citizen_user`;
DROP VIEW IF EXISTS `smartmsph`.`rep_citizen_user` ;
USE `smartmsph`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `smarthmsph`.`rep_citizen_user` AS select `c`.`id` AS `idcitizen`,`c`.`citizenname` AS `citizenname`,`c`.`surname1` AS `surname1`,`c`.`surname2` AS `surname2`,`c`.`mail` AS `mail`,`c`.`phoneNumber` AS `phoneNumber`,`u`.`id` AS `iduser`,`u`.`username` AS `username`,`u`.`password` AS `password`,`u`.`role` AS `role`,`u`.`citizen_id` AS `citizen_id` from (`smarthmsph`.`citizen` `c` join `smarthmsph`.`citizen_user` `u` on((`c`.`id` = `u`.`citizen_id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
